support licenses in other SPDX format (#387)
## 📝 Description

Allow libs with license format `(<l1> AND <l2>)` to be builded (mmkv had
that case)
- checks license field in package.json (like previously)
- if grep (<l1> AND <l2>)
  - checks if both licenses are supported
    - it true, then builds and adds to .pom file both licenses 

I haven't used any npm package for SPDX format validation or implemented
handling for all possible SPDX formats, as there was no need for it in
the current situation (one package was the only problem). If this
becomes an issue later, we can consider introducing a more comprehensive
solution.

#379

## 🧪 Testing

before
```
error: License (MIT AND BSD-3-Clause) is not allowed for react-native-mmkv. Allowed licenses are: MIT, Apache-2.0, BSD-3-Clause, BSD-3-Clause-Clear, BSD-2-Clause. You can configure a custom license with MD5 hash verification in libraries.json.
```
after
```
✅ Successfully built AAR for react-native-mmkv@3.3.0 with RN 0.83.0
```