[LIBS] Remove nitro libs for stability (#189)
## 📝 Description

Remove libs based on nitro libs due to unstable cpp

- react-native-iap
  - removing
    - ```
      * What went wrong:
Cannot locate tasks that match ':react-native-iap:bundleReleaseAar' as
task 'bundleReleaseAar' is ambiguous in
project ':react-native-iap'. Candidates are: 'bundleAmazonReleaseAar',
'bundleAmazonReleaseLocalLintAar',
      'bundlePlayReleaseAar', 'bundlePlayReleaseLocalLintAar'.
      ```
  - includes nitro from 14.0.0, can support lower versions then
  - https://www.npmjs.com/package/react-native-iap?activeTab=versions
- v12.16 (without nitro) have +10k weekly downloads, so worth supporting
- react-native-mmkv
  - includes nitro from v4, can support lower versions then
  - https://www.npmjs.com/package/react-native-mmkv?activeTab=versions
- v3.x (without nitro) have +300k weekly downloads, so worth supporting
  - ``` 
      error: License (MIT AND BSD-3-Clause) is not allowed. 
      Allowed licenses are: MIT, Apache-2.0, BSD-3-Clause, BSD-2 Clause
     ```
- react-native-unistyles
  - removing
- react-native-nitro-sound
  - removing

## 🎯 Type of Change

- [x] 🧩 New library support