Fix failing builds on react-native@0.85.0
When all packages in project were substitued with prebuilt .xcframeworks, the build started failing with:
```
<path>/AwesomeProject/ios/AwesomeProject/AppDelegate.swift:2:8: error: no such module 'React'
import React
       ^
```

The reason for that was that the XCode assumed the pods without source files (because rnrepo clean those) meant that those doesnt have to take part in the build process at all, and thus did not include the necessary build settings for the React Native framework.

To fix that, I added the dummy header as a source files, which forces XCode to propagate info about the React Native framework to the main app target. Header will not create any additional binary code and build time overhead is negligible.