[BOT] Update React Native versions (#311)
## 🚀 React Native Version Update

This PR updates the React Native versions list with newly released
versions.

_This is an automated PR generated by the daily version check workflow._

## 0.85.0 changes

- add new version to react-native-versions list (0.85.0)
- install proper reanimated version for rngh to build (previous was too
old)
- fix issues with building on ios (more below)

#### Failing ios builds on rn0.85.0

When all packages in project were substitued with prebuilt
.xcframeworks, the build started failing with:
```
<path>/AwesomeProject/ios/AwesomeProject/AppDelegate.swift:2:8: error: no such module 'React'
import React
       ^
```

The reason for that was that the XCode assumed the pods without source
files (because rnrepo clean those) meant that those doesnt have to take
part in the build process at all, and thus did not include the necessary
build settings for the React Native framework.

To fix that, I added the dummy header as a source files, which forces
XCode to propagate info about the React Native framework to the main app
target. Header will not create any additional binary code and build time
overhead is negligible.

Tested with:
```
  "dependencies": {
    "react": "19.2.3",
    "react-native": "0.85.0",
    "@react-native/new-app-screen": "0.85.0",
    "@rnrepo/build-tools": "../packages/build-tools",
    "react-native-safe-area-context": "5.7.0",
    "react-native-reanimated": "4.3.0",
    "react-native-gesture-handler": "2.31.1",
    "react-native-worklets": "0.8.1",
    "react-native-screens": "4.24.0"
  },
```

---------

Co-authored-by: radoslawrolka <128408457+radoslawrolka@users.noreply.github.com>
Co-authored-by: Radosław Rolka <radoslaw.rolka@gmail.com>